// utils/seriesKeywords.js
export const FormulaCarSeriesKeywords = ["Formula", "Skip Barber", "US Open Wheel", "Grand Prix Legends", "F4"];
export const SportsCarSeriesKeywords = [
        "GT Thrustmaster Challenge",
        "Ring Meister",
        "LMP3",
        "Clio",
        "Sports Car Challenge",
        "European Sprint",
        "Kamel GT",
        "Supercars",
        "Touring Car",
        "GT Challenge",
        "Lotus",
        "Mission R",
        "Stock Car Brasil",
        "Radical Racing Challenge",
        "Ferrari",
        "Global Fanatec",
        "Mazda",
        "Spec Racer Ford",
        "Clio",
        "LMP2",
        "VRS Series",
        "GR",
        "Production Car Sim",
        "Porsche Cup",
        "GT3",
        "GT4",
        "GTE",
        "IMSA",
        "INDYCAR",
        "GT Endurance",
        "GT Sprint",
        "CONSPIT",
        "TCR",
        "BMW M Power",
        "Radical",
        "SRX",
        "Weekly Race Challenge",
];
export const OvalSeriesKeywords = [
        "NASCAR",
        "Truck",
        "Xfinity",
        "INDYCAR",
        "ARCA",
        "Super Late Model Series",
        "Silver Crown",
        "SK Modified",
        "Tour Modified",
        "Street Stock Fanatec",
        "PickUp Cup",
        "Legends Series",
        "Carburetor Cup",
        "Late Model Stock Tour",
        "Advanced Legends Cup",
        "Dallara Dash",
        "Street Stock Next Level Racing Series",
        "Big Block Modified",
        "Draft Master",
        "Gen 4 Cup",
        "Rookie Legends VRS",
];
export const DirtRoadSeriesKeywords = ["iRX", "Rookie Pro", "Pro 4 Off", "Pro 2 Off", "Pro Lite", "Pro 2 Lite", "Pro 4 Lite", "Rallycross"];
export const DirtOvalSeriesKeywords = ["Dirt Legends", "USAC", "World of Outlaws", "Sprint Car Cup", "Dirt Super Late", "Dirt 410", "Midget", "DIRTcar", "WoO", "Micro", "Legends Cup"];
