export const seriesList = [
        "USAC 360 Sprint Car Series - 2024 Season 3",
        "iRacing Porsche Cup By Coach Dave Delta - 2024 Season 3",
        "Ring Meister Ricmotech Series - Fixed - 2024 Season 3",
        "Dirt Midget Cup - 2024 Season 3",
        "Clio Cup - 2024 Season 3 - Fixed",
        "Formula C - Thrustmaster Dallara F3 Series -2024 Season 3-Fixed",
        "DIRTcar UMP Modified Series - 2024 Season 3 - Fixed",
        "Formula B - Super Formula IMSIM Series - 2024 Season 3",
        "NASCAR Tour Modified Series - Fixed - 2024 Season 3 - Fixed",
        "World of Outlaws Late Model Series - 2024 Season 3",
        "Street Stock Next Level Racing Series - C - 2024 Season 3",
        "BMW M Power Tour - Fixed - 2024 Season 3 - Fixed",
        "Rallycross Series - Fixed - 2024 Season 3",
        "Skip Barber Race Series - 2024 Season 3",
        "Super Late Model Series - Fixed - 2024 Season 3 - Fixed",
        "Big Block Modified Series - Fixed - 2024 Season 3",
        "Pro 4 Off-Road Racing Series - 2024 Season 3",
        "FIA Formula 4 Challenge- 2024 Season 3 - Fixed",
        "FIA F4 Esports Regional Tour - Europe - 2024 Season 3",
        "Rookie Pro 2 Lite Off-Road Racing Series - Fixed - 2024 Season 3",
        "Dirt Super Late Model Tour - Fixed - 2024 Season 3",
        "INDYCAR Series - Oval - Fixed - 2024 Season 3",
        "NASCAR Class A - 2024 Season 3",
        "iRacing Classic Lotus Grand Prix- 2024 Season 3",
        "Radical Esports Cup - Fixed - 2024 Season 3",
        "Gen 4 Cup - Fixed - 2024 Season 3 Fixed",
        "Sprint Car Cup - 2024 Season 3",
        "GT4 Falken Tyre Challenge - 2024 Season 3 Fixed",
        "FIA F4 Esports Regional Tour  - Asia Pacific - 2024 Season 3",
        "Rookie Micro Winged Sprint Car Series - Fixed - 2024 Season 3",
        "Dallara Formula iR - Fixed - 2024 Season 3",
        "FIA F4 Esports Regional Tour  - Americas - 2024 Season 3",
        "DIRTcar 360 Sprint Car Series  2024 Season 3",
        "NASCAR Class B Fixed - 2024 Season 3 Fixed ",
        "Global Fanatec Challenge - 2024 Season 3 - Fixed",
        "Rallycross Series - 2024 Season 3",
        "Pro 2 Off-Road Racing Series - Fixed - 2024 Season 3",
        "Big Block Modified Series - 2024 Season 3",
        "IMSA iRacing Series - 2024 Season 3",
        "SK Modified Series - 2024 Season 3 - Fixed",
        "DIRTcar Pro Late Model Series - Fixed - 2024 Season 3",
        "Formula C - Super Formula Lights - Fixed - 2024 Season 3",
        "Mustang Skip Barber  Challenge - 2024 Season 3 - Fixed",
        "LMP3 Trophy - Fixed - 2024 Season 3",
        "Grand Prix Legends - 2024 Season 3",
        "NASCAR Legends Series - 2024 Season 3 Fixed",
        "US Open Wheel D - USF 2000 Series  - 2024 Season 3 - Fixed",
        "Super Late Model Series - 2024 Season 3",
        "INDYCAR Series - Fixed - 2024 Season 3",
        "Dirt Midget Cup - Fixed - 2024 Season 3",
        "Rookie DIRTcar SS MOZA Racing - Fixed 2024 Season 3",
        "DIRTcar 360 Sprint Car  Series - Fixed 2024 Season 3",
        "Formula C - DOF Reality Dallara F3 Series - 2024 Season 3",
        "US Open Wheel C - Indy Pro 2000 Series - 2024 Season 3",
        "IMSA Vintage Series - 2024 Season 3",
        "World of Outlaws Sprint Car Series - 2024 Season 3 - Fixed",
        "Dirt 410 Sprint Car Tour - Fixed - 2024 Season 3",
        "DIRTcar 358 Modified Series 2024 Season 3",
        "CARS Late Model Stock Tour - 2024 Season 3",
        "Advanced Legends Cup - 2024 Season 3",
        "World of Outlaws Late Model Series - 2024 Season 3 - Fixed",
        "Draft Master SIMAGIC Series - Fixed 2024 Season 3",
        "FIA Formula 4 Challenge - 2024 Season 3",
        "GTE Sprint CONSPIT Series - 2024 Season 3",
        "ARCA Menards Series - 2024 Season 3 - Fixed",
        "Proto-GT Thrustmaster Challenge - 2024 Season 3",
        "Formula Vee SIMAGIC Series - 2024 Season 3 Fixed",
        "Rain Master - 2024 Season 3 - Fixed",
        "Stock Car Brasil - 2024 Season 3 - Fixed",
        "World of Outlaws Sprint Car Series - 2024 Season 3",
        "TCR Virtual Challenge - Fixed - 2024 Season 3",
        "DIRTcar Limited Late Model Series - 2024 Season 3 Fixed",
        "Carburetor Cup - 2024 Season 3",
        "INDYCAR Series - 2024 Season 3",
        "Street Stock Fanatec Series - R - 2024 Season 3 Fixed",
        "Pro 4 Off-Road Racing Series - Fixed - 2024 Season 3",
        "Formula A - Grand Prix Series - Fixed - 2024 Season 3",
        "CARS Late Model Stock Tour - Fixed - 2024 Season 3",
        "Rookie Legends Cup  - 2024 Season 3",
        "Ferrari GT3 Challenge - 2024 Season 3 - Fixed",
        "NASCAR Class C Maconi Series - Fixed - 2024 Season 3",
        "Mission R Challenge - 2024 Season 3 - Fixed",
        "Global Mazda MX-5 Fanatec Cup - 2024 Season 3 Fixed",
        "Formula 1600 Rookie Sim-Motion Series - 2024 Season 3 Fixed",
        "Silver Crown Cup - 2024 Season 3",
        "Outlaw Micro Showdown 2024 Season 3",
        "Falken Tyre Sports Car Challenge - 2024 Season 3",
        "Dirt Legends Cup - 2024 Season 3",
        "AMSOIL USAC Sprint Car - Fixed 2024 - Season 3",
        "TCR Virtual Challenge - 2024 Season 3",
        "Advanced Mazda MX-5 Cup Series - 2024 Season 3",
        "IMSA iRacing Series - Fixed - 2024 Season 3",
        "PickUp Cup - 2024 Season 3",
        "SRX Series - Fixed - 2024 Season 3",
        "Formula 1600 Thrustmaster Trophy - 2024 Season 3",
        "DIRTcar Class C Dirt Street Stock Series - 2024 Season 3 Fixed",
        "Formula A - Grand Prix Series - 2024 Season 3",
        "Formula C - Super Formula Lights - 2024 Season 3",
        "Pro 2 Off-Road Racing Series - 2024 Season 3",
        "Supercars Series - 2024 Season 3",
        "SK Modified Weekly Series - 2024 Season 3",
        "Dallara Dash - 2024 Season 3",
        "DIRTcar Pro Late Model Series - 2024 Season 3",
        "GR Buttkicker Cup - 2024 Season 3 - Fixed",
        "DIRTcar 305 Sprint Car Fanatec Series - 2024 Season 3 Fixed",
        "Rookie iRX Volkswagen Beetle Lite - Fixed - 2024 Season 3",
        "iRX Volkswagen Beetle Lite - 2024 Season 3",
        "NASCAR Class A Fixed - 2024 Season 3 Fixed",
        "GT Sprint Simucube Series - 2024 Season 3",
        "Rookie Micro Non Wing Sprint Car Series - Fixed - 2024 Season 3",
        "GT3 Fanatec Challenge - Fixed - 2024 Season 3 - Fixed",
        "Formula B - Super Formula IMSIM Series - Fixed - 2024 Season 3",
        "LMP2 Prototype Challenge  - 2024 Season 3 - Fixed",
        "Supercars Series - Australian Servers - 2024 Season 3",
        "NASCAR Tour Modified Series - 2024 Season 3",
        "iRacing Porsche Cup By Coach Dave Delta - Fixed - 2024 Season 3",
        "Production Car Sim-Lab Challenge - 2024 Season 3",
        "Spec Racer Ford Challenge - 2024 Season 3",
].sort();
